FROM balenalib/%%RESIN_MACHINE_NAME%%-debian

RUN install_packages dnsmasq wireless-tools python3-dev python3-psutil python3-pip

WORKDIR /usr/src/app

RUN curl https://api.github.com/repos/balena-io/wifi-connect/releases/latest -s \
    | grep -hoP 'browser_download_url": "\K.*%%RESIN_ARCH%%\.tar\.gz' \
    | xargs -n1 curl -Ls \
    | tar -xvz -C /usr/src/app/

# Upgrade pip
RUN pip3 install --upgrade pip

RUN pip3 install graphyte

COPY . ./

CMD ["bash", "scripts/start.sh"]